Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: bucket
  BucketS3Arn:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: bucketArn
      Type: String
      Value: !GetAtt MyBucket.Arn
  BucketS3Name:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: bucketName
      Type: String
      Value: !Ref MyBucket.Name
