Resources:
  ThisIsAUniqueBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: cedricuniquename
  BucketS3Arn:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: bucketuniquearn
      Type: String
      Value: !GetAtt ThisIsAUniqueBucket.Arn
  BucketS3Name:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: bucketuniquename
      Type: String
      Value: !Ref ThisIsAUniqueBucket
